# Generated by Django 5.2.13 on 2026-04-26 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemetric',
            options={'verbose_name': '게임 지표', 'verbose_name_plural': '게임 지표들'},
        ),
        migrations.RemoveField(
            model_name='gamemetric',
            name='marketing_hook',
        ),
        migrations.RemoveField(
            model_name='gamemetric',
            name='not_for_personas',
        ),
        migrations.RemoveField(
            model_name='gamemetric',
            name='one_line_summary',
        ),
        migrations.RemoveField(
            model_name='gamemetric',
            name='similar_games',
        ),
        migrations.RemoveField(
            model_name='gamemetric',
            name='target_personas',
        ),
        migrations.RemoveField(
            model_name='gamemetric',
            name='unique_selling_points',
        ),
        migrations.AddField(
            model_name='game',
            name='ai_curation_summary',
            field=models.TextField(blank=True, default='', help_text='게임의 핵심 매력 한 줄 평', verbose_name='AI 큐레이션 요약'),
        ),
        migrations.AddField(
            model_name='game',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_early_access',
            field=models.BooleanField(default=False, verbose_name='얼리 액세스'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='무료 게임'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_indie',
            field=models.BooleanField(default=True, verbose_name='인디 게임'),
        ),
        migrations.AddField(
            model_name='game',
            name='marketing_hook',
            field=models.TextField(blank=True, default='', verbose_name='마케팅 훅'),
        ),
        migrations.AddField(
            model_name='game',
            name='not_for_personas',
            field=models.JSONField(blank=True, default=list, verbose_name='비추천 페르소나'),
        ),
        migrations.AddField(
            model_name='game',
            name='one_line_summary',
            field=models.TextField(blank=True, default='', verbose_name='한 줄 요약'),
        ),
        migrations.AddField(
            model_name='game',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='리뷰 수'),
        ),
        migrations.AddField(
            model_name='game',
            name='similar_games',
            field=models.JSONField(blank=True, default=list, verbose_name='유사 게임'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_positive_ratio',
            field=models.FloatField(blank=True, help_text='0.0 ~ 1.0', null=True, verbose_name='스팀 긍정 비율'),
        ),
        migrations.AddField(
            model_name='game',
            name='target_personas',
            field=models.JSONField(blank=True, default=list, verbose_name='타겟 페르소나'),
        ),
        migrations.AddField(
            model_name='game',
            name='unique_selling_points',
            field=models.JSONField(blank=True, default=list, verbose_name='핵심 셀링 포인트'),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='gem_potential',
            field=models.FloatField(blank=True, help_text='AI 평가 잠재력 (0~10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='analysis_method',
            field=models.CharField(choices=[('gpt5.4_batch', 'GPT-5.4 Batch (원본 4,190개)'), ('fewshot_5.4based', 'Few-Shot (5.4 데이터 기반)'), ('manual', '수동 입력'), ('pending', '대기 중')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_analyzed',
            field=models.BooleanField(default=False, help_text='분석 완료 여부'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='action_pacing',
            field=models.FloatField(blank=True, help_text='액션 템포 (높을수록 빠름)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='analysis_summary',
            field=models.TextField(blank=True, default='', help_text='분석 요약'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='choice_consequence',
            field=models.FloatField(blank=True, help_text='선택의 결과 중요도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='competitive_stress',
            field=models.FloatField(blank=True, help_text='경쟁 스트레스', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='분석 신뢰도 (0~1)', null=True),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='coop_synergy',
            field=models.FloatField(blank=True, help_text='협동 시너지', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='core_loop',
            field=models.TextField(blank=True, default='', help_text='핵심 게임 루프'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='cozy_factor',
            field=models.FloatField(blank=True, help_text='아늑함/편안함 (동물의 숲, 스타듀밸리)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='dark_fantasy_vibe',
            field=models.FloatField(blank=True, help_text='다크 판타지 분위기', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='data_limitations',
            field=models.TextField(blank=True, default='', help_text='데이터 한계점'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='environmental_storytelling',
            field=models.FloatField(blank=True, help_text='환경 스토리텔링', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='epic_scale',
            field=models.FloatField(blank=True, help_text='서사적 규모감', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='exploration_reward',
            field=models.FloatField(blank=True, help_text='탐험 보상감', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='extraction_version',
            field=models.CharField(default='gpt5.4-batch-v1', help_text='추출 버전 (gpt5.4-batch-v1, fewshot-v1 등)', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='freedom_level',
            field=models.FloatField(blank=True, help_text='자유도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='genre_classification',
            field=models.CharField(blank=True, default='', help_text='장르 분류', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='gore_level',
            field=models.FloatField(blank=True, help_text='고어/잔인함 수준', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='grind_factor',
            field=models.FloatField(blank=True, help_text='노가다/반복 요소', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='growth_reward',
            field=models.FloatField(blank=True, help_text='성장 보상감', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='has_base_building',
            field=models.BooleanField(default=False, help_text='기지 건설'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='has_crafting',
            field=models.BooleanField(default=False, help_text='제작 시스템'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='has_permadeath',
            field=models.BooleanField(default=False, help_text='영구 사망'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='horror_factor',
            field=models.FloatField(blank=True, help_text='공포 강도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='humor_rating',
            field=models.FloatField(blank=True, help_text='유머/코믹 요소', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='is_anime_style',
            field=models.BooleanField(default=False, help_text='애니메이션 스타일'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='is_first_person',
            field=models.BooleanField(default=False, help_text='1인칭 시점'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='is_real_time',
            field=models.BooleanField(default=False, help_text='실시간 게임'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='is_retro_aesthetic',
            field=models.BooleanField(default=False, help_text='레트로 미학'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='is_third_person',
            field=models.BooleanField(default=False, help_text='3인칭 시점'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='is_turn_based',
            field=models.BooleanField(default=False, help_text='턴제 게임'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='learning_curve',
            field=models.FloatField(blank=True, help_text='학습 곡선 (높을수록 어려움)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='lore_richness',
            field=models.FloatField(blank=True, help_text='세계관/로어 깊이', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='management_complexity',
            field=models.FloatField(blank=True, help_text='관리 복잡도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='melancholy',
            field=models.FloatField(blank=True, help_text='우울함/멜랑콜리', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='metric_justifications',
            field=models.JSONField(blank=True, default=dict, help_text='지표별 판단 근거'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='multiplayer_scale',
            field=models.FloatField(blank=True, help_text='멀티플레이어 규모', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='narrative_linearity',
            field=models.FloatField(blank=True, help_text='서사 선형성 (1=비선형, 10=완전 선형)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='npc_interaction',
            field=models.FloatField(blank=True, help_text='NPC 상호작용 깊이', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='platforming_precision',
            field=models.FloatField(blank=True, help_text='플랫포밍 정밀도 요구', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='puzzle_complexity',
            field=models.FloatField(blank=True, help_text='퍼즐 복잡도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='raw_content',
            field=models.JSONField(blank=True, default=dict, help_text='content 원본 JSON'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='raw_reasoning',
            field=models.JSONField(blank=True, default=dict, help_text='reasoning 원본 JSON'),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='reflex_demand',
            field=models.FloatField(blank=True, help_text='반사신경 요구도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='rng_dependency',
            field=models.FloatField(blank=True, help_text='운/랜덤 의존도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='session_length',
            field=models.FloatField(blank=True, help_text='세션 길이 (1=짧음, 10=매우 김)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='soundtrack_impact',
            field=models.FloatField(blank=True, help_text='사운드트랙 영향력', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='stealth_importance',
            field=models.FloatField(blank=True, help_text='스텔스 중요도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='strategic_depth',
            field=models.FloatField(blank=True, help_text='전략적 깊이', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='time_pressure',
            field=models.FloatField(blank=True, help_text='시간 압박감', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='user_creation',
            field=models.FloatField(blank=True, help_text='유저 창작 요소', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='visual_spectacle',
            field=models.FloatField(blank=True, help_text='시각적 화려함', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['app_id'], name='games_app_id_54fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_analyzed', 'analysis_method'], name='games_is_anal_881d07_idx'),
        ),
    ]
