# Generated by Django 5.2.13 on 2026-05-11 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamemetric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemetric',
            name='animation_quality',
            field=models.FloatField(blank=True, help_text='애니메이션 품질', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='art_style_uniqueness',
            field=models.FloatField(blank=True, help_text='아트 스타일 독창성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='audio_design',
            field=models.FloatField(blank=True, help_text='오디오 디자인', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='build_variety',
            field=models.FloatField(blank=True, help_text='빌드 다양성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='community_dependency',
            field=models.FloatField(blank=True, help_text='커뮤니티 의존도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='difficulty_accessibility',
            field=models.FloatField(blank=True, help_text='난이도 접근성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='endgame_content',
            field=models.FloatField(blank=True, help_text='엔드게임 콘텐츠', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='modding_support',
            field=models.FloatField(blank=True, help_text='모딩 지원', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='monetization_fairness',
            field=models.FloatField(blank=True, help_text='과금 공정성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='narrative_depth',
            field=models.FloatField(blank=True, help_text='서사 깊이', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='progression_clarity',
            field=models.FloatField(blank=True, help_text='진행 명확성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='replay_value',
            field=models.FloatField(blank=True, help_text='리플레이 가치', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='save_flexibility',
            field=models.FloatField(blank=True, help_text='저장 유연성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='tutorial_quality',
            field=models.FloatField(blank=True, help_text='튜토리얼 품질', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='ui_ux_polish',
            field=models.FloatField(blank=True, help_text='UI/UX 완성도', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamemetric',
            name='world_reactivity',
            field=models.FloatField(blank=True, help_text='월드 반응성', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gamemetric',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='분석 신뢰도 (0~1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
