# Generated by Django 5.2.13 on 2026-05-24 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저들'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 활동'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taste_dna_json',
            field=models.JSONField(blank=True, null=True, verbose_name='취향 DNA (JSON)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_clicks',
            field=models.IntegerField(default=0, verbose_name='총 클릭 수'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_ratings',
            field=models.IntegerField(default=0, verbose_name='총 평가 수'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_searches',
            field=models.IntegerField(default=0, verbose_name='총 검색 수'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Steam ID'),
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='세션 ID')),
                ('app_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Steam App ID')),
                ('action_type', models.CharField(choices=[('search', '검색어 입력'), ('detail_view', '게임 상세 조회'), ('rec_click', '추천 결과 클릭'), ('search_click', '검색 결과 클릭'), ('steam_click', 'Steam으로 이동'), ('like', '좋아요'), ('neg_feedback', '취향 안 맞음 피드백'), ('revisit', '재방문 (같은 게임)')], db_index=True, max_length=30, verbose_name='행동 종류')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='컨텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발생 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '유저 행동',
                'verbose_name_plural': '유저 행동 목록',
                'db_table': 'user_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_ua_user_time'), models.Index(fields=['app_id', 'action_type'], name='idx_ua_app_action'), models.Index(fields=['session_id', '-created_at'], name='idx_ua_session_time')],
            },
        ),
    ]
