# Generated by Django 5.2.14 on 2026-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s_plus', '50대 이상')], max_length=20, null=True, verbose_name='나이대'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타'), ('no_answer', '응답 안 함')], max_length=20, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='온보딩 완료'),
        ),
    ]
