# Generated by Django 5.2.15 on 2026-06-30 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_age_group_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True, verbose_name='게임 app_id')),
                ('played', models.BooleanField(help_text='True=해봤어요, False=안 해봤어요', verbose_name='플레이 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '게임 설문',
                'verbose_name_plural': '게임 설문 목록',
                'db_table': 'game_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(help_text='cozy_factor 등 game_metrics 컬럼명', max_length=50, verbose_name='지표 키')),
                ('our_score', models.FloatField(help_text='GPT가 매긴 0~10 점수', verbose_name='우리 점수')),
                ('user_score', models.IntegerField(help_text='유저 슬라이더 응답 1~5', verbose_name='유저 체감')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.gamesurvey', verbose_name='설문')),
            ],
            options={
                'verbose_name': '지표 평가',
                'verbose_name_plural': '지표 평가 목록',
                'db_table': 'metric_ratings',
            },
        ),
        migrations.AddIndex(
            model_name='gamesurvey',
            index=models.Index(fields=['user', 'app_id'], name='idx_survey_user_game'),
        ),
        migrations.AddConstraint(
            model_name='gamesurvey',
            constraint=models.UniqueConstraint(fields=('user', 'app_id'), name='uq_user_game_survey'),
        ),
        migrations.AddIndex(
            model_name='metricrating',
            index=models.Index(fields=['metric'], name='idx_rating_metric'),
        ),
    ]
