# Generated by Django 5.2.15 on 2026-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metric_preferences',
            field=models.JSONField(blank=True, default=dict, help_text="예: {'cozy_factor': 5, 'horror_factor': 1}", verbose_name='지표 선호도'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_genres',
            field=models.JSONField(blank=True, default=list, help_text="예: ['액션', 'RPG', '전략']", verbose_name='선호 장르'),
        ),
    ]
