# Generated by Django 5.2.15 on 2026-07-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_metric_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesurvey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
